version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
    vendor: true
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly