web: spring stop && rm tmp/pids/* tmp/cache/* -rf; bundle exec rails s -p 3000
webpacker: rm ../tmp/* -rf && WEBPACKER_DEV_SERVER_HOST=localhost WEBPACKER_DEV_SERVER_PORT=8765 WEBPACKER_DEV_SERVER_PUBLIC=localhost:8765 bundle exec ../bin/webpack-dev-server
